#

pluginName = fr.se301b.taskset Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_TaskSet_type = Task Set
_UI_Task_type = Task
_UI_Connection_type = Connection
_UI_Port_type = Port
_UI_NamedElement_type = Named Element
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_TaskSet_schedulingPolicy_feature = Scheduling Policy
_UI_TaskSet_task_feature = Task
_UI_TaskSet_connection_feature = Connection
_UI_Task_threadKind_feature = Thread Kind
_UI_Task_period_feature = Period
_UI_Task_port_feature = Port
_UI_Connection_maxQueueLen_feature = Max Queue Len
_UI_Connection_dstPort_feature = Dst Port
_UI_Connection_sourcePort_feature = Source Port
_UI_Port_direction_feature = Direction
_UI_Port_datatype_feature = Datatype
_UI_NamedElement_name_feature = Name
_UI_NamedElement_qualifiedName_feature = Qualified Name
_UI_Unknown_feature = Unspecified

_UI_Datatype_int_literal = int
_UI_Datatype_float_literal = float
_UI_Datatype_character_literal = character
_UI_ThreadKind_sporadic_literal = sporadic
_UI_ThreadKind_periodic_literal = periodic
_UI_PortDirection_in_literal = in
_UI_PortDirection_out_literal = out
_UI_SchedulingPolicy_RMS_literal = RMS
_UI_Task_behavior_feature = Behavior
